CREATE TABLE CLIENTES (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2 (200) NOT NULL,
    email VARCHAR (200) UNIQUE
);

INSERT INTO CLIENTES (nome, email) VALUES ('Nicolas Rocha', 'nicolasrocha@senac.sp');
INSERT INTO CLIENTES (nome, email) VALUES ('Afonso Lelis', 'afonsinholelis@snec.sp');
INSERT INTO CLIENTES (nome, email) VALUES ('Aryanne Jadma', 'aryannejadma@senac.sp');


SELECT ID, NOME, EMAIL FROM CLIENTES;


CREATE TABLE PRODUTOS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2 (200) NOT NULL,
    preco NUMBER (10,2) NOT NULL  CHECK (preco >= 0),
    tipo VARCHAR2 (20) NOT NULL
);


INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Notebook ASUS', 1000.20, 'Notebook');
INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Iphone 11', 1500.00,  'Celular');
INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Notebook ACER', 1200.00, 'Notebook');


SELECT ID, NOME, PRECO, TIPO FROM PRODUTOS;


-- Utilizei merge para fazer a atualizacao dos produtos tipo "notebook" em 10%. USING foi utilizado para descrever que eu ia usar o SELECT para selecionar as linhas preco e tipo da tabela produtos  
--Aquele np foi uma abreviacao de TIPO "notebook"  da tabela PRODUTOS .
-- O MATCHED é para juntas as que sao iguais, exemplo a linha NOTEBOOK.


MERGE INTO produtos
USING (
  SELECT id, preco
  FROM produtos WHERE tipo = 'Notebook'
) np
ON (produtos.id = np.id)
WHEN MATCHED THEN
  UPDATE SET preco = np.preco * 1.10;



CREATE TABLE PEDIDOS (
  id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cliente_id NUMBER NOT NULL,
  produto_id NUMBER NOT NULL,
  status     VARCHAR2(20) NOT NULL CHECK (status IN ('ABERTO','FINALIZADO','CANCELADO'))
);


INSERT INTO PEDIDOS (cliente_id, PRODUTO_ID, STATUS) VALUES ('21','21','CANCELADO');
INSERT INTO PEDIDOS (cliente_id, PRODUTO_ID, STATUS) VALUES ('22', '22', 'ABERTO');


SELECT cliente_id, PRODUTO_ID, STATUS FROM PEDIDOS ;

DELETE PEDIDOS WHERE status = 'CANCELADO';