FOTO DO FLUXOGRAMA DE RELACIONAMENTO:

[image](https://drive.google.com/file/d/1emYOWEVFCVQwI1rvkYYB5d8Gt0FTMwJj/view?usp=sharing)




CODIGO CRIADO:

-- TABELA DE MATERIAS PRIMAS QUE SAO NESCESSARIAS PARA NOSSO CONCRETO.SELECT.
CREATE TABLE MATERIA_PRIMA (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME VARCHAR (200) NOT NULL
)
--TABELA DE FORNECEDORES DE MATERIAS PRIMAS.
CREATE TABLE FORNECEDORES (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL
);
-- TABELA RELACIONATIVA DE N:N (FORNECEDOR X MATERIA PRIMA FORNECIDA).
CREATE TABLE FORNECE (
    ID_FORNECEDOR NUMBER NOT NULL REFERENCES FORNECEDORES (ID),
    ID_MATERIA NUMBER NOT NULL REFERENCES MATERIA_PRIMA(ID),
    PRIMARY KEY (ID_FORNECEDOR, ID_MATERIA_PRIMA)
)
-- RECEITAS PARA TIPO DE CONCRETO.
CREATE TABLE RECEITAS (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TIPO_DE_CONCRETO VARCHAR (100)NOT NULL,
    DESCRICAO_CONCRETO VARCHAR(200) NOT NULL
)
--TABELA DE ASSOCIACAO MATERIA PRIMA PARA TIPO DE CONCRETO, TABELA DE ORGANIZACAO DA CRIACAO.
CREATE TABLE CONCRETO (
    ID_MATERIA_USADA NUMBER NOT NULL REFERENCES MATERIA_PRIMA (ID),
    ID_RECEITA NUMBER NOT NULL REFERENCES RECEITAS(ID)
)





-- TABELAS PARA CONTROLE DE NOSSOS FUNCIONARIOS E SUAS AREAS DE ATUACAO.
CREATE TABLE GERENTES(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME VARCHAR (100)NOT NULL
)
--SETORES CONCRETO+
CREATE TABLE SETORES_DE_PRODUCAO(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME_SETOR VARCHAR(100)NOT NULL,
    ID_GERENTE_RESPONSAVEL NUMBER NOT NULL REFERENCES GERENTES(ID)
)
--FUNCIONARIOS SETORES 
CREATE TABLE FUNCIONARIOS (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    ID_SETOR_ATUACAO NUMBER NOT NULL REFERENCES SETORES_DE_PRODUCAO(ID),
    ENTREGADOR VARCHAR (10) NOT NULL

)
--ENTREGADORES (EXCLUSIVA PARA FUNCIONARIOS QUE FAZEM ENTREGAS)
CREATE TABLE ENTREGADORES (
    ID_FUNCIONARIO NUMBER NOT NULL REFERENCES FUNCIONARIOS (ID),
    CNH VARCHAR2(20) NOT NULL,
    TIPO_VEICULO VARCHAR2(50),
    VALIDADE_CNH DATE
)


-- TABELAS SOBRE NOSSOS CLIENTES, PEDIDOS DE LOTES E ETC.
CREATE TABLE CLIENTES (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100)NOT NULL,
    ENDERECO VARCHAR (100) NOT NULL
)

CREATE TABLE PEDIDOS_LOTES (
    ID NUMEBR GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL REFERENCES CLIENTE (ID),
    QUANTIDADE NUMBER(3) NOT NULL,
    DATA DATE NOT NULL
)
CREATE TABLE ENVIO(
    ID_ENTREGA NUMBER NOT NULL REFERENCES PEDIDOS_LOTES(ID),
    ID_ENTREGADOR NUMBER NOT NULL REFERENCES ENTREGADORES(ID),
    DATA DATE NOT NULL
)



RESPOSTA DAS QUESTOES: 

1- Por que a normalização foi essencial para a integridade dos dados da fábrica?

A normalização teve importância para prevenir os erros na geração desse projeto de banco de dados, me auxiliando a entender qual a necessidade que cada projeto precisava, manter os recursos necessários para cada entidade.

2- Em que situações a desnormalização se torna uma escolha estratégica, e não um 
erro?

Creio que a desnormalização se torna algo “errado” a partir do momento em que a pessoa aplica errado, seja por falta de conhecimento ou apenas por erro de compreensão do código ou das necessidades que esse projeto exige. Entretanto, sei que existe um cenário em que ela pode ser usada como vantagem, seja para poupar recursos ou redundância.

3-Quais riscos a tabela desnormalizada pode trazer? Como você mitigaria esses riscos?

Uma tabela desnormalizada pode trazer riscos como inconsistência de dados, redundância, maior dificuldade de manutenção e confusão em consultas complexas. Esses problemas ocorrem porque a duplicação de informações aumenta as chances de erros e dificulta a integridade do banco.
Para mitigar esses riscos, é importante iniciar a análise da tabela em um fluxograma, identificando as entidades e suas dependências funcionais. Em seguida, aplicar progressivamente as formas normais (1FN, 2FN, 3FN, 4FN) de acordo com as necessidades do projeto, de modo a reduzir a redundância e garantir maior consistência e confiabilidade nos dados.

4- Qual seria o impacto de não aplicar a BCNF neste cenário?

O principal seria a inconsistência de dados, não íamos conseguir realizar uma pesquisa simples, pois haveria redundância de dados, gerando pesquisas confusas direcionando para 1 ou mais entidades diferentes. Uma sequência de outros erros poderiam acontecer com a falta desse recurso.

